name: MCBEMovie
main: itsu.mcbe.mcbemovie.core.MCBEMovie
version: 2.1.0
author: Itsu
api: ["1.0.0"]

commands: 
  movie: 
    description: "MCBEMovieのコマンドです。マップ上で動画を再生します。 /movie [giveme | play]"